[package]
name = "windows-app-sdk"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.43.0"
features = [
    "implement",
    "Foundation",
]

[build-dependencies]
windows-bindgen = "0.43.0"
windows-metadata = "0.43.0"
thiserror = "1.0.38"
